//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplomado_MVC_UASD_Estudiante_ImageUpload2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblEstudiante2
    {
        public int EstudianteId { get; set; }
        [Required(ErrorMessage = "El nombre es obligatorio")]
        [MinLength(3, ErrorMessage ="El nombre debe tener al menos tres caracteres")]
        public string Nombres { get; set; }

        [Required(ErrorMessage = "El Apellido es obligatorio")]
        [MinLength(3, ErrorMessage = "El Apellido debe tener al menos tres caracteres")]
        public string Apellidos { get; set; }

        [Required(ErrorMessage = "La direccion es obligatoria")]
        [MinLength(3, ErrorMessage = "La direccion debe tener al menos tres caracteres")]
        public string Direccion { get; set; }

        [Required(ErrorMessage = "El Telefono es obligatorio")]
        [MinLength(10, ErrorMessage = "El Telefono debe tener al menos diez caracteres")]
        public string Telefono { get; set; }

        [Required(ErrorMessage = "La Cedula es obligatoria")]
        [MinLength(11, ErrorMessage = "La Cedula debe tener al menos once caracteres")]
        public string Cedula { get; set; }

        [Required(ErrorMessage = "La foto es obligatoria")]
        
        public string ImageUrl { get; set; }
    }
}
